IF NOT EXISTS(SELECT * FROM [GEN_LIST] WHERE [ID] = 1)
BEGIN
	SET IDENTITY_INSERT [DBO].[GEN_LIST] ON
	INSERT [DBO].[GEN_LIST] ([ID], [LIST_NAME]) 
	VALUES (1, N'Incident Status') 
	SET IDENTITY_INSERT [DBO].[GEN_LIST] OFF
END
GO

IF NOT EXISTS(SELECT * FROM [GEN_LIST_ITEM] WHERE [ID] = 1)
BEGIN
	SET IDENTITY_INSERT [DBO].[GEN_LIST_ITEM] ON
	INSERT [DBO].[GEN_LIST_ITEM] ([id], [LIST_ID], [LIST_ITEM])
	VALUES (1, 1, N'In progress')
	SET IDENTITY_INSERT [DBO].[GEN_LIST_ITEM] OFF
END
GO

IF NOT EXISTS(SELECT * FROM [GEN_LIST_ITEM] WHERE [ID] = 2)
BEGIN
	SET IDENTITY_INSERT [DBO].[GEN_LIST_ITEM] ON
	INSERT [DBO].[GEN_LIST_ITEM] ([id], [LIST_ID], [LIST_ITEM])
	VALUES (2, 1, N'Closed')
	SET IDENTITY_INSERT [DBO].[GEN_LIST_ITEM] OFF
END
GO