name: Deploy Node.js to Azure Web App

# this was '[push]' in the suggested file
on:
  push:
    branches:
      - Development

# CONFIGURATION
# For help,  go to  https://github.com/Azure/Actions
#
# 1. Set up the following secrets in your repository:
#   AZURE_WEBAPP_PUBLISH_PROFILE
#
# 2. Change these variables for your configuration:
env:
  # Test Deployment Settings
  # AZURE_WEBAPP_NAME: testTeamBoardTab
  # Prod Deployment Settings

  AZURE_WEBAPP_NAME: TeamBoardTabProd

  AZURE_WEBAPP_PACKAGE_PATH: "." # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: "18.x" # set this to the node version to usess

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production # this was   'dev' in the suggested file test
    steps:
      - uses: actions/checkout@v3 # this was '@master' in the suggested file
      - name: Use Node.js ${{ env.NODE_VERSION }} # this was 'Set up Node.js version' in my original file
        uses: actions/setup-node@v3 # this was 'v1' in the suggested file
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: npm install, build, and test
        # this section was different in my original file
        run: |
          # Build and test the project, then
          # deploy to Azure Web App.
          npm prune --production
          npm install --legacy-peer-deps
          npm run build --if-present
          # npm run test --if-present
      - name: "Deploy to Azure WebApp"
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          slot-name:
            "Production" # <-- this property wasn't in suggested file
            #Test  Deployment Settings
          #  publish-profile: ${{ secrets.AZURE_WEB_APP_TEST_OLD_PUBLISH_PROFILE }} # taken  from original file
          #Prod Deployment Settings

          publish-profile: ${{ secrets.AZURE_WEB_APP_PROD_PUBLISH_PROFILE }} # taken  from original file

          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  # For more information on GitHub Actions for Azure , refer to https://github.com/Azure/Actions
  # For more samples to get started with GitHub Action workflows to deploy to Azure, refer to https://github.com/Azure/actions-workflow-samples
